config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.connect '/sections/:section_id/rooms/:room_id/dialogue_line/:id/', :controller=>'media_objects', :action=>'update_media'

  map.resources :game_robots

  map.resources :guides

  map.resources :speakers

  map.resources :media_objects

  map.minimap '/sections/:section_id/rooms/:id/minimap', :controller => 'rooms', :action => 'minimap'
  map.section_map '/sections/:section_id/rooms/:id/section_map', :controller => 'rooms', :action => 'section_map'
  map.worldmap '/sections/:section_id/worldmap', :controller => 'sections', :action => 'worldmap'
  map.article_map '/sections/:section_id/article_map', :controller => 'sections', :action => 'article_map'
  map.journal '/games/:game_id/journal.:format', :controller => 'games', :action => 'journal'
  
  map.resources :games

  map.resources :sections do |section|
    section.resources :rooms do |room|
      room.resources :doors
      room.resources :dialogue_lines
    end
  end

  
  map.root :controller => 'games'
 
  # Note: These default routes make all actions in every controller accessible via GET requests. You should
  # consider removing the them or commenting them out if you're using named routes and resources.
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/dialogue_line.rb
class DialogueLine < ActiveRecord::Base
  acts_as_nested_set :scope => :room
  validates_presence_of :line_generator_id
  validates_presence_of :line_generator_type
  validates_presence_of :content
#  validates_uniqueness_of :content  TODO Find out why this is here?

  named_scope :visible_at_start, :conditions => {:visible => true}
  named_scope :guides_only, :conditions => {:line_generator_type => "Guide"}
  named_scope :speakers_only, :conditions => {:line_generator_type => "Speaker"}

# These next two make the necessary associations for has_many_polymorphs
  belongs_to :room
  belongs_to :line_generator, :polymorphic => true


  has_and_belongs_to_many :games, :join_table => "visible_dialogue_lines_media_objects"


  has_and_belongs_to_many :disposed_of_dialogue_lines, :class_name=>"DialogueLine", :join_table => "disposed_of_dialogue_lines",
    :foreign_key=>"game_id",:association_foreign_key=>"dialogue_line_id"
  has_and_belongs_to_many :invisible_dialogue_lines,:class_name=>"DialogueLine", :join_table =>"visible_dialogue_lines_invisible_dialogue_lines",
    :foreign_key=>"visible_dialogue_line_id",:association_foreign_key=>"invisible_dialogue_line_id"

  has_and_belongs_to_many :media_objects
  has_and_belongs_to_many :doors

#  TODO do we really need this? to access the root dialogue line for a whole room
  def self.room_root(room_id)
    find_by_room_id(room_id).root unless find_by_room_id(room_id).nil?
  end
  

#  to access all conversation root dialogue lines in a given room
#  This may not be necessary now that conversation_root is active.
  def self.conversation_roots(room)
    roots.find(:all, :conditions => ["room_id = ?", room.id])
  end

#  TODO currently taking care of this in controller for room with multiple roots
#  to access a particular conversation root dialogue line in a given room
  def self.conversation_root(room)
    conversation_roots(room.id).find_by_line_generator_id_and_line_generator_type(self.line_generator_id, self.line_generator_type)
  end


  def before_save
    self.content=Sanitize.clean(self.content, :elements => ['a','br','strong','em','u'],
      :attributes => {'a' => ['href']},
      :protocols => {'a' => {'href' => ['http', 'https']}})
  end
  
end

app/controllers/dialogue_lines_controller.rb
require 'sanitize'

class DialogueLinesController < ApplicationController

  before_filter :authenticate
  rescue_from ::NoMethodError, :with=>:no_method_recover
  # GET /dialogue_lines
  # GET /dialogue_lines.xml
  uses_tiny_mce :options => {
                              :theme=>'advanced',
                              :theme_advanced_disable=>'underline,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,outdent,indent,image,cleanup,help,hr,removeformat,formatselect,fontselect,fontsizeselect,styleselect,sub,sup,forecolor,backcolor,forecolorpicker,backcolorpicker,charmap,visualaid,anchor,newdocument,blockquote,separator',

                              :theme_advanced_buttons1 => 'bold,italic,cut,copy,paste,link,unlink,code',
                              :theme_advanced_buttons2 => "",
                              :theme_advanced_buttons3 => "",


                              :force_br_newlines=>'true',
                              :forced_root_block=>''

                            }


 




  def index
    @section = Section.find(params[:section_id])
    @room = Room.find(params[:room_id])

    
    

    @dialogue_lines = DialogueLine.find(:all,
      :conditions=> ["room_id = ? and parent_id is NULL",params[:room_id]] )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dialogue_lines }
    end
  end

  # GET /dialogue_lines/1
  # GET /dialogue_lines/1.xml
  def show
     @section=Section.find(params[:section_id])
     @room = Room.find(params[:room_id])
     @dialogue_line = DialogueLine.find(params[:id])
     @media_objects = MediaObject.find(:all, 
       :conditions => ['dialogue_line_id = ?', @dialogue_line.id],
       :joins => :dialogue_lines)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dialogue_line }
    end
  end

  # GET /dialogue_lines/new
  # GET /dialogue_lines/new.xml
  def new
    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    
    #@media_objects=@room.media_objects.find(:all)

    @dialogue_line = DialogueLine.new
    @all_generators = LineGenerator.find(:all,
                                        :select=>"line_generator_type",
                                        :group=>"line_generator_type")
  

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dialogue_line }
    end
  end

  # GET /dialogue_lines/1/edit
  def edit
    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    @dialogue_line = DialogueLine.find(params[:id])

    








    @all_generators = LineGenerator.find(:all,
                                        :select=>"line_generator_type",
                                        :group=>"line_generator_type")


   
    @existing_generator = @dialogue_line.line_generator_type.constantize.find(:all, :order=>'name')

    @media_objects=MediaObject.find(:all, :conditions=>['dialogue_line_id = ?', @dialogue_line.id], :joins=>:dialogue_lines)
    
    @doors=Door.find(:all, :conditions=>['dialogue_line_id = ?', @dialogue_line.id], :joins=>:dialogue_lines)


    #@guides = Guide.find(:all, :conditions=>["id IN (?)", @root_lines_visible.map(&:line_generator_id)])

   
   
    @triggered_ids=DialogueLine.find(:all,
      :select=>"invisible_dialogue_line_id",
      :from=>"visible_dialogue_lines_invisible_dialogue_lines",
      :conditions=>["visible_dialogue_line_id = ?",@dialogue_line.id])

    @triggered_dialogue_lines = DialogueLine.find(:all,
      :conditions=>["id IN (?)",@triggered_ids.map(&:invisible_dialogue_line_id)]
    )



   

    #@triggered_dialogue_lines=DialogueLine.find(:all, :conditions=>['id IN (?)',@triggered_ids.id],
      #:joins=>:invisible_dialogue_lines)

    #    All the doors in the room, found through the has_many :through helpers
    
    
  end

  # POST /dialogue_lines
  # POST /dialogue_lines.xml
  def create

    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    @dialogue_line = DialogueLine.new(params[:dialogue_line])
    


    respond_to do |format|
      if @dialogue_line.save
        flash[:message] = 'DialogueLine was successfully created.'
        
#        The string conditional below must match the submit text in new.html.erb
        format.html { redirect_to( params[:commit] == "Save line and return to list" ?
              section_room_dialogue_lines_path(@section, @room) : 
              new_section_room_dialogue_line_path(@section, @room)) }
        
        format.xml  { render :xml => @dialogue_line, :status => :created, :location => @dialogue_line }
      else
        #format.html { render :action => "new" }
        #format.xml  { render :xml => @dialogue_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dialogue_lines/1
  # PUT /dialogue_lines/1.xml
  def update

    

    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    @dialogue_line = DialogueLine.find(params[:id])
    
      if @dialogue_line.update_attributes(params[:dialogue_line])
        
        flash[:message] = "Dialogue line successfully updated."
        redirect_to(section_room_dialogue_lines_path(@section, @room))

      else
        flash[:notice] = "There was an error saving the dialogue line."

      end

  end

  # DELETE /dialogue_lines/1
  # DELETE /dialogue_lines/1.xml
  def destroy
    @dialogue_line = DialogueLine.find(params[:id])
    @dialogue_line.destroy

    respond_to do |format|
      format.html { redirect_to(section_room_dialogue_lines_path) }
      format.xml  { head :ok }
    end
  end

  def restructure

    @section = params[:section_id]
    @room = params[:room_id]
    _parent = DialogueLine.find(params[:dialogue_line_id].gsub('dialogue_line_',''))
    _child = DialogueLine.find(params[:subcategory_id].gsub('dialogue_line_',''))
    _child.move_to_child_of(_parent)

    
    



    @dialogue_lines = DialogueLine.find(:all,
     :conditions=> ["room_id = ? and parent_id is NULL",params[:room_id]] )
    
    if request.xhr?
        render :update do |page|
      page.redirect_to(:action=>'index', :room_id=>@room, :section_id=>@section)
    end
    end
    
    #render :partial => 'dialogue_lines_tree',
           #:locals=>{:dialogue_lines=>@dialogue_lines}

  rescue ActiveRecord::ActiveRecordError
    logger.error("Attempt to put a parent into its child")
    flash[:notice]="You can't put a parent into its child!"
    render :update do |page|
      page.redirect_to(:action=>'index', :room_id=>@room, :section_id=>@section)
    end  
  end

  def make_root
    @section = params[:section_id]
    @room = params[:room_id]

    DialogueLine.find(params[:dialogue_line_id]).move_to_root

    
    redirect_to(section_room_dialogue_lines_path(@section,@room))
    
  end

  def copy_line
    @section = params[:section_id]
    @room = params[:room_id]
    
    copy_line = DialogueLine.find(params[:dialogue_line_id])


    my_line = DialogueLine.new
    my_line.content = copy_line.content
    my_line.line_generator_id = copy_line.line_generator_id
    my_line.line_generator_type = copy_line.line_generator_type
    my_line.room_id = copy_line.room_id
    my_line.visible = copy_line.visible
    my_line.save

    redirect_to(section_room_dialogue_lines_path(@section,@room))
    
  end


  def find_generators
    @generators = params[:value].constantize.find(:all, :order=>'name')
  end


  def select_media_objects

    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    @dialogue_line = DialogueLine.find(params[:id])

  end

  def select_doors

    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    @dialogue_line = DialogueLine.find(params[:id])

  end

  def select_invisible_dialogue_lines

    @section=Section.find(params[:section_id])
    @room = Room.find(params[:room_id])
    @dialogue_line = DialogueLine.find(params[:id])

  end


private

  def no_method_recover
    render :partial => "problem"
  end


end

app/helpers/dialogue_lines_helper.rb
module DialogueLinesHelper

  def add_door_img_dl(direction, room)
    image_tag "door-arrow-#{direction}.gif", :alt => "Door to #{room.name}", :title => "Door to #{room.name}"
  end

  def add_door_img_dl_small(direction, room)
    image_tag "door-arrow-#{direction}-small.gif", :alt => "Door to #{room.name}", :title => "Door to #{room.name}"
  end

end

app/views/dialogue_lines/_add_generators.html.erb
<div id="build_toggle_extra_space" class="build_menu">
    <%= link_to_function(image_tag("up.png",:title=>"show/hide more",:alt=>"show/hide more"),
            "$('build_menu').toggle(); $('build_toggle_extra_space').toggle();")%>
    <%= link_to_function "Build",
            "$('build_menu').toggle(); $('build_toggle_extra_space').toggle();"%>
   </div>



<div id="build_menu" style="display:none" class="build_menu">

  <%= link_to_function(image_tag("down.png",:title=>"show/hide more",:alt=>"show/hide more"),
            "$('build_menu').toggle(); $('build_toggle_extra_space').toggle();")%>

      <%= link_to_function "Hide",
            "$('build_menu').toggle(); $('build_toggle_extra_space').toggle();"%>


  <h3>Build Menu</h3>

<%current_uri = request.env['PATH_INFO']%>

  <% if current_uri =~/rooms\//  %>

    <%my_room="no"%>
  <%else  %>
    <%my_room="yes"%>
  <%end%>

<% if current_uri!="/sections" && my_room!="yes"%>
     Lines:<br />
    <%= link_to 'New line for this room', new_section_room_dialogue_line_path(@section,@room) -%>

    
    <br />
    <br />
    
    <%= link_to 'Line list for this room',  section_room_dialogue_lines_path(@section,@room) %>
    <br />
    <br />
    Sections:<br />
    <%= link_to 'All sections in game', sections_path -%>

    <br />
    <br />
    Rooms:<br />
    <%= link_to 'Rooms in this section', section_rooms_path(@section) -%>


    <br />
    <br />


    <%end%>
    Guides:<br />
    <%=link_to  "New", new_guide_path, :class=>"lightview",:rel=>"iframe", :title=>"Guides:: :: width: 400, height: 800"  %>
    &nbsp;|
    <%=link_to  "Edit/Destroy", guides_path, :class=>"lightview",:rel=>"iframe", :title=>"Guides:: :: width: 400, height: 800"  %>

    <br />
    Speakers:<br />
    <%=link_to  "New", new_speaker_path, :class=>"lightview",:rel=>"iframe", :title=>"Speakers:: :: width: 400, height: 800"  %>
    &nbsp;|

    <%=link_to  "Edit/Destroy", speakers_path, :class=>"lightview",:rel=>"iframe", :title=>"Speakers:: :: width: 400, height: 800"  %>

    <br />
    Media Objects:<br />
    <%=link_to  "New", new_media_object_path, :class=>"lightview",:rel=>"iframe", :title=>"Media Objects:: :: width: 400, height: 800"  %>
    &nbsp;|
    <%=link_to  "Edit/Destroy", media_objects_path, :class=>"lightview",:rel=>"iframe", :title=>"Media Objects:: :: width: 400, height: 800"  %>
    <br />
    
    
    


    <br />
    


    

  </div>

app/views/dialogue_lines/_dialogue_line_row.html.erb
<% room=Room.find(params[:room_id]) %>

<%top_entrance = room.entrances.find_by_door_direction('vertical')  %>
<%left_entrance = room.entrances.find_by_door_direction('horizontal')  %>
<%bottom_exit = room.exits.find_by_door_direction('vertical')  %>
<%right_exit = room.exits.find_by_door_direction('horizontal')  %>



  
  <tr  style="cursor: move;"  id="dialogue_line_<%= dialogue_line.id -%>" >
   

    <td valign="top" width="25px">

      <% triggered_ids=DialogueLine.find(:all,
      :select=>"invisible_dialogue_line_id",
      :from=>"visible_dialogue_lines_invisible_dialogue_lines",
      :conditions=>["visible_dialogue_line_id = ?",dialogue_line.id])%>

      <%if triggered_ids.size>0 %>
    <%triggered_dialogue_lines = DialogueLine.find(:all,
      :conditions=>["id IN (?)",triggered_ids.map(&:invisible_dialogue_line_id)])
      %>





    <% myhover ="|"%>
        <%triggered_dialogue_lines.each do |line|  %>

    <%- myhover << line.content + " | " -%>

    

        <% end %>
      <%= image_tag("dialogue_swap.png", :border=>0,:alt=>"#{myhover}",:title=>"#{myhover}") %>
      <% end %>
      
    </td>

  <td valign="top" width="25px">
    <%-doors=Door.find(:all, :conditions=>['dialogue_line_id = ?', dialogue_line.id], :joins=>:dialogue_lines)  -%>
    <% doors.each do |door| %>

      <% if top_entrance %>
          <% if door.id == top_entrance.id %>
        <%= add_door_img_dl_small("top",door.parent_room) %>
        <% end %>
        <% end %>
          
  <% if bottom_exit %>
  <% if door.id == bottom_exit.id  %>
            <%= add_door_img_dl_small("bottom",door.child_room) %>
    <% end %>
        <% end %>
  <% if left_entrance %>
  <% if door.id == left_entrance.id  %>
                <%= add_door_img_dl_small("left",door.parent_room) %>

    <% end %>
        <% end %>
<% if right_exit %>
  <% if door.id == right_exit.id %>
                    <%= add_door_img_dl_small("right",door.child_room) %>
    <% end %>
        <% end %>

      <% end %>
   

  </td>

  <td valign="top" width="25px">
      <%- media_instances = MediaObject.count_by_sql("SELECT COUNT(*) FROM dialogue_lines_media_objects where dialogue_line_id = '#{dialogue_line.id}'") -%>



      <% if media_instances >= 1 %>

        <%- media_names = MediaObject.find(:all, :select=>"short_name",
          :conditions=>["dialogue_line_id = ?", dialogue_line.id], :joins=>:dialogue_lines) -%>

        <% myhover ="|"%>

        <%-media_names.each do |name|  %>
              <%- myhover << name.short_name + "|" -%>
        <%end%>

        <%= image_tag("media-object.gif", :border=>0,:alt=>"#{myhover}",:title=>"#{myhover}") %><%= "("+"#{media_instances}"+")" %>

      <% end %>
  </td>
  <td valign="top" width="25px">

    <% if dialogue_line.content.length > 75 %>
      <%= link_to_function(image_tag("my_toggle.png",:title=>"show/hide more",:alt=>"show/hide more"),
            "$('content-#{dialogue_line.id}').toggle(); $('stub-#{dialogue_line.id}').toggle();")-%>
          <% end %>
  </td>
  

  <% if dialogue_line.visible == false %>
<td id="content_field" class="utterance" style="padding-left: <%= (2 * dialogue_line.level) + 1 -%>em;" width="400" bgcolor="#cccccc">

  <% else %>
  <td id="content_field" class="utterance" style="padding-left: <%= (2 * dialogue_line.level) + 1 -%>em;" width="400">
    <% end %>

  <% if dialogue_line.level==0 %>
    <span class="root">root:</span>
      <% end %>
<% if dialogue_line.content.length > 75 %>
  <%="<div id='stub-#{dialogue_line.id}'>"-%>
    <% my_stub=truncate(dialogue_line.content,75," . . . ")-%>
     <%= lightview_link(my_stub) -%>
     <% else%>
    
    <%= lightview_link(dialogue_line.content) -%>
    <% end %>
  </div>
    


    

    

    <%="<div id='content-#{dialogue_line.id}' style='display:none;'>"-%>
    


      
      <%= lightview_link(dialogue_line.content) -%>
    </div>
    
  </td>

  <td valign="top" class="utterer" width="50px">
      <% generator_name  = dialogue_line.line_generator_type.constantize.find(:all,
        :select=>"name",
        :conditions=> ["id = ?", dialogue_line.line_generator_id]) %>

      <%=h generator_name[0].name-%>
  </td>
  
  <td valign="top" class="utterer">
      <%= link_to "Duplicate",{:action=>"copy_line",:dialogue_line_id => dialogue_line.id, :room_id=>@room, :section_id=>@section}%>|
      <%= link_to 'Edit', edit_section_room_dialogue_line_path(@section,@room,dialogue_line), :method=>:get-%> |
      <%= link_to 'Destroy', section_room_dialogue_line_path(@section,@room,dialogue_line), :confirm=>"Are you sure?  When you delete this line, you'll delete all its children too.", :method=>:delete-%>
      


      <%if dialogue_line.level != 0  %>
        | <%= link_to "Make_root",{:action=>"make_root",:dialogue_line_id => dialogue_line.id, :room_id=>@room, :section_id=>@section}%>
      <%end%>
  </td>
</tr>
<%= draggable_element(
      "dialogue_line_#{dialogue_line.id}",
      :ghosting => true,
      :revert => true,
      :scroll=> "window"
    )
-%>
<%= drop_receiving_element(
       "dialogue_line_#{dialogue_line.id}",
       #:update => 'catlist',
       :with => "'subcategory_id=' + element.id",
       :url => { :action => 'restructure', :dialogue_line_id => dialogue_line.id, :room_id=>@room,:section_id=>@section },
       :hoverclass => "row_highlight"
     )
-%>
<%- dialogue_line.children.each do |subcat| -%>
  <%= render :partial => 'dialogue_line_row', :locals => {:dialogue_line => subcat} -%>
<%- end -%>

app/views/dialogue_lines/_dialogue_lines_tree.html.erb
 
  
  
<%- @dialogue_lines.each do |dialogue_line| -%>

  <%  if dialogue_line.parent_id.blank?%>


<div id=<%="Root_Id_#{dialogue_line.id}_toggle_extra_space"%> style="display:none" class="line_menu">
    <%= link_to_function(image_tag(dialogue_line.line_generator.thumbnail.url(:small),
        :title=>"show",:alt=>"show"),
            "$('Root_Id_#{dialogue_line.id}').toggle(); $('Root_Id_#{dialogue_line.id}_toggle_extra_space').toggle();")%>
    <%= link_to_function truncate(dialogue_line.content, :length => 20),
            "$('Root_Id_#{dialogue_line.id}').toggle(); $('Root_Id_#{dialogue_line.id}_toggle_extra_space').toggle();"%>
   </div>




<div id=<%="Root_Id_#{dialogue_line.id}"%> class="line_menu" >
  <%= link_to_function(image_tag(dialogue_line.line_generator.thumbnail.url(:small),:title=>"hide",:alt=>"hide"),
            "$('Root_Id_#{dialogue_line.id}').toggle(); $('Root_Id_#{dialogue_line.id}_toggle_extra_space').toggle();")%>

      <%= link_to_function "Hide this conversation",
            "$('Root_Id_#{dialogue_line.id}').toggle(); $('Root_Id_#{dialogue_line.id}_toggle_extra_space').toggle();"%>





  <table>

    <thead>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>

        <th >Line</th>
        <th >Generator</th>
        <td></td>

      </tr>
    </thead>
    <tbody id="catlist">
      <%= render :partial => 'dialogue_line_row', :locals => {:dialogue_line => dialogue_line} -%>
      </tbody>
    </table>
  </div>








  <% end %>
  <% end %>
 


 

app/views/dialogue_lines/_generators.html.erb
<p>Line Generator Id <br />
<select id="dialogue_line_line_generator_id" name="dialogue_line[line_generator_id]">

 <%= render(:partial =>"select_options") %>

</select>
</p>

app/views/dialogue_lines/_select_options.html.erb
<%@generators.each do |generator|  %>

  <%="<option value=\"" + "#{generator.id}\""+">"+"#{generator.name}"+"</option>" %>

<% end %>

app/views/dialogue_lines/_update_invisible_dialogue.html.erb
<h4>Dialogue this line triggers</h4>



<table>
<tr>
  
  <th>Content . . .</th>
  

</tr>
<% @triggered_dialogue_lines.each do |dialogue_line| %>
<tr>
  <td><%=dialogue_line.content  %></td>
</tr>
 <% end %> 


</table>
<%= link_to 'Edit Dialogue-Line Trigger(s)', url_for(:controller=>"dialogue_lines",:action=>"select_invisible_dialogue_lines",
  :section_id=>@section,:room_id=>@room,:id=>@dialogue_line)%>

app/views/dialogue_lines/_update_result.html.erb
<p>You've successfully edited the line.</p>


<form>
<input type=button value="Close This Window" onClick="javascript: parent.Lightview.hide();">
</form>

app/views/dialogue_lines/index.html.erb
<%if session[:authenticated]=="yes" %>

<%=render :partial=>'add_generators'%>

<%end%>

<h1>Dialogue Lines</h1>
<p>Drag and drop a line to nest it under another.  You can move lines among conversations.</p>
<p>Room name: <%=  link_to @room.name, section_room_path(@section,params[:room_id]) %></p>

<%- if @dialogue_lines.empty? -%>
  <p><em>No lines have been created yet.</em></p>
<%- else -%>

 
      <%= render :partial => 'dialogue_lines_tree', :locals => {:dialogue_lines => @dialogue_lines} -%>



  
    <% end  %>

app/views/dialogue_lines/select_doors.html.erb
Select doors that this dialogue line unlocks.  If you don't want to make changes, click Select to return to the previous page.

<% form_for([@section,@room,@dialogue_line]) do |f|  %>

<%= hidden_field_tag "dialogue_line[door_ids][]", "" %>
<table>
  <tr><td></td><th>Door to room . . .</th><td></td>
</tr>
<% for door in Door.find_all_by_child_room_id(params[:room_id]) %>
  
<tr>

    <td><%= check_box_tag "dialogue_line[door_ids][]", door.id, @dialogue_line.doors.include?(door) %>
    </td>


  <td><%=door.parent_room.name %>
    </td>

    <td>
      <% if door.door_direction == "vertical" %>
        <%= add_door_img_dl("top",door.parent_room) %>
      <%else%>
        <%= add_door_img_dl("left",door.parent_room) %>
      <% end %>

    </td>
    
  

</tr>
<% end %>

<% for door in Door.find_all_by_parent_room_id(params[:room_id]) %>

<tr>
 

    <td><%= check_box_tag "dialogue_line[door_ids][]", door.id, @dialogue_line.doors.include?(door) %>
    </td>


  <td><%=door.child_room.name %>
    </td>

     <td><% if door.door_direction == "vertical" %>
        <%= add_door_img_dl("bottom",door.child_room) %>
      <%else%>
        <%= add_door_img_dl("right",door.child_room) %>
      <% end %>
    </td>
</tr>

  <% end %>


  

</table>
<%= f.submit 'Select' %>
<% end %>

  

app/views/dialogue_lines/select_invisible_dialogue_lines.html.erb
Select invisible dialogue lines this dialogue line triggers.  If you don't want to make changes, click Select to return to the previous page.

<% form_for([@section,@room,@dialogue_line]) do |f|  %>

<%= hidden_field_tag "dialogue_line[invisible_dialogue_line_ids][]", "" %>
<table>
<% for invisible_dialogue_line in DialogueLine.find(:all, :conditions=>["visible = ? and room_id = ?", false,@room.id]) %>

<tr>

    <td><%= check_box_tag "dialogue_line[invisible_dialogue_line_ids][]",
            invisible_dialogue_line.id, @dialogue_line.invisible_dialogue_lines.include?(invisible_dialogue_line) %>
    </td>

        <td><%= invisible_dialogue_line.content %></td>

</tr>
  <% end %>




</table>
<%= f.submit 'Select' %>
<% end %>

app/views/dialogue_lines/select_media_objects.html.erb
Select media objects.  If you don't want to make changes, click Select to return to the previous page.

<% form_for([@section,@room,@dialogue_line]) do |f|  %>

<%= hidden_field_tag "dialogue_line[media_object_ids][]", "" %>
<table>
<% for media_object in MediaObject.find(:all) %>

<tr>

    <td><%= check_box_tag "dialogue_line[media_object_ids][]", media_object.id, @dialogue_line.media_objects.include?(media_object) %>
    </td>

<td><%= link_to image_tag(media_object.thumbnail.url(:medium), :border=>0),"#{media_object.url}", :class=>"lightview",
          :title=>"#{media_object.short_name}:: :: width: #{media_object.object_width}, height: #{media_object.object_height}"  %>
  </td>
  <td><%=h media_object.name %>
    </td>
  <td><%=h media_object.short_name %>
    </td>
  <td><%=h media_object.url %>
    </td>

</tr>
  <% end %>


  

</table>
<%= f.submit 'Select' %>
<% end %>

  